name: Azure python 3.5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.5.10
    - uses: actions/setup-python@v1
      with:
        python-version 3.5.10
        - name:Install dependecies
        run:|
          make install
        - name:Lint
        run:|
          make lint
        -name:test
        run:|
          make test
    
